<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABP.Core.Domain\ABP.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\Beneficiaries\" />
    <Folder Include="Dtos\Transactions\" />
    <Folder Include="Features\Beneficiaries\Commands\CreateBeneficiary\" />
    <Folder Include="Features\Beneficiaries\Commands\DeleteBeneficiary\" />
    <Folder Include="Features\Beneficiaries\Commands\UpdateBeneficiary\" />
    <Folder Include="Features\Beneficiaries\Queries\" />
    <Folder Include="Features\Transactions\Commands\CreateTransaction\" />
    <Folder Include="Features\Transactions\Commands\DeleteTransaction\" />
    <Folder Include="Features\Transactions\Commands\UpdateTransaction\" />
    <Folder Include="Features\Transactions\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Mappings\EntitiesAndDtos\TransactionMappingProfile.cs" />
  </ItemGroup>

</Project>
